
const HANDLE_REPRESENTATIVE = 'HANDLE_REPRESENTATIVE_RETURN_DATA'
const HANDLE_ELECTION_BY_ADDRESS = 'HANDLE_ELECTION_BY_ADDRESS_RETURN_DATA'
const HANDLE_ADDRESS_LOOKUP = 'HANDLE_ADDRESS_LOOKUP'
const LOOKUP_ADDRESS = 'LOOKUP_ADDRESS'
const HANDLE_PARALLAX_DATA = 'HANDLE_PARALLAX_DATA'
export {
    HANDLE_REPRESENTATIVE,
    HANDLE_ADDRESS_LOOKUP,
    HANDLE_ELECTION_BY_ADDRESS,
    LOOKUP_ADDRESS,
    HANDLE_PARALLAX_DATA
}
