
const HANDLE_REPRESENTATIVE = 'HANDLE_REPRESENTATIVE_RETURN_DATA'
const HANDLE_ELECTION_BY_ADDRESS = 'HANDLE_ELECTION_BY_ADDRESS_RETURN_DATA'
const LOOKUP_ADDRESS = 'LOOKUP_ADDRESS'
export {
    HANDLE_REPRESENTATIVE,
    HANDLE_ELECTION_BY_ADDRESS,
    LOOKUP_ADDRESS
}
